#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Push_FireBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JI")]
	public partial class JiDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Inserttbl_FB_SendLog(tbl_FB_SendLog instance);
    partial void Updatetbl_FB_SendLog(tbl_FB_SendLog instance);
    partial void Deletetbl_FB_SendLog(tbl_FB_SendLog instance);
    #endregion
		
		public JiDataClassesDataContext() : 
				base(global::Push_FireBase.Properties.Settings.Default.JIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JiDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JiDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JiDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JiDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_FB_SendLog> tbl_FB_SendLog
		{
			get
			{
				return this.GetTable<tbl_FB_SendLog>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_FB_SendCommited")]
		public int proc_FB_SendCommited([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FB_SendLogId", DbType="Int")] System.Nullable<int> fB_SendLogId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fB_SendLogId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_User_ParamFBClear")]
		public int proc_User_ParamFBClear([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, key);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_FB_SendLog")]
	public partial class tbl_FB_SendLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FB_SendLogId;
		
		private System.Nullable<System.DateTime> _FB_SendLogDateAdd;
		
		private System.Nullable<System.DateTime> _FB_SendLogDateSend;
		
		private System.Nullable<int> _userid;
		
		private string _key;
		
		private string _Title;
		
		private string _Body;
		
		private int _userid_whosend;
		
		private int _ObjId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFB_SendLogIdChanging(int value);
    partial void OnFB_SendLogIdChanged();
    partial void OnFB_SendLogDateAddChanging(System.Nullable<System.DateTime> value);
    partial void OnFB_SendLogDateAddChanged();
    partial void OnFB_SendLogDateSendChanging(System.Nullable<System.DateTime> value);
    partial void OnFB_SendLogDateSendChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnkeyChanging(string value);
    partial void OnkeyChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void Onuserid_whosendChanging(int value);
    partial void Onuserid_whosendChanged();
    partial void OnObjIdChanging(int value);
    partial void OnObjIdChanged();
    #endregion
		
		public tbl_FB_SendLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_SendLogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FB_SendLogId
		{
			get
			{
				return this._FB_SendLogId;
			}
			set
			{
				if ((this._FB_SendLogId != value))
				{
					this.OnFB_SendLogIdChanging(value);
					this.SendPropertyChanging();
					this._FB_SendLogId = value;
					this.SendPropertyChanged("FB_SendLogId");
					this.OnFB_SendLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_SendLogDateAdd", DbType="DateTime")]
		public System.Nullable<System.DateTime> FB_SendLogDateAdd
		{
			get
			{
				return this._FB_SendLogDateAdd;
			}
			set
			{
				if ((this._FB_SendLogDateAdd != value))
				{
					this.OnFB_SendLogDateAddChanging(value);
					this.SendPropertyChanging();
					this._FB_SendLogDateAdd = value;
					this.SendPropertyChanged("FB_SendLogDateAdd");
					this.OnFB_SendLogDateAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_SendLogDateSend", DbType="DateTime")]
		public System.Nullable<System.DateTime> FB_SendLogDateSend
		{
			get
			{
				return this._FB_SendLogDateSend;
			}
			set
			{
				if ((this._FB_SendLogDateSend != value))
				{
					this.OnFB_SendLogDateSendChanging(value);
					this.SendPropertyChanging();
					this._FB_SendLogDateSend = value;
					this.SendPropertyChanged("FB_SendLogDateSend");
					this.OnFB_SendLogDateSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[key]", Storage="_key", DbType="VarChar(255)")]
		public string key
		{
			get
			{
				return this._key;
			}
			set
			{
				if ((this._key != value))
				{
					this.OnkeyChanging(value);
					this.SendPropertyChanging();
					this._key = value;
					this.SendPropertyChanged("key");
					this.OnkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(1024)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid_whosend", DbType="Int NOT NULL")]
		public int userid_whosend
		{
			get
			{
				return this._userid_whosend;
			}
			set
			{
				if ((this._userid_whosend != value))
				{
					this.Onuserid_whosendChanging(value);
					this.SendPropertyChanging();
					this._userid_whosend = value;
					this.SendPropertyChanged("userid_whosend");
					this.Onuserid_whosendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjId", DbType="Int NOT NULL")]
		public int ObjId
		{
			get
			{
				return this._ObjId;
			}
			set
			{
				if ((this._ObjId != value))
				{
					this.OnObjIdChanging(value);
					this.SendPropertyChanging();
					this._ObjId = value;
					this.SendPropertyChanged("ObjId");
					this.OnObjIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
